services:
  - type: web
    name: analisis-bibliometrico
    env: python
    rootDir: .   # ahora la ra√≠z es el proyecto
    buildCommand: "python -m pip install --upgrade pip && python -m pip install -r requirements.txt"
    startCommand: "PYTHONPATH=backend python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11

